### ISSUE TITLE
Producing a few PCB's, ready to go?

### ISSUE THREAD

**Issue by ErichStyger** [martinribelotta/imxrt1020-module#7]
I have ordered samples, and I want to go ahead and produce a few PCB's for first prototypes.
I just want to check and ask if this is a good idea now or I better should wait if some pending changes are up in the pipe?

**Comment by martinribelotta** [comment]
In this days Im checking the 6mil-6mil (commit a4b0decba3ec175cee2b18ca15bfa11b3555eea9) with more cheap route. Let me do the final check (in two or tree days more) and enable you to make a prototype with this.

I maintain this issue opened for signaling the start of prototiping :smiley:

**Comment by ErichStyger** [comment]
great, thank you!

**Comment by ErichStyger** [comment]
closing old issues
